### ISSUE TITLE
Returned datetime is naive

### ISSUE THREAD

**Issue by Lexicality** [dairiki/lektor-git-timestamp#5]
First of all, thank you for this plugin.
I'm using it to generate a sitemap for my website, but I've run into a small issue where the datetime is naive and the sitemap specification requires the `lastmod` field to have a timezone. I have a workaround in place, but I'd prefer not to use one!
The basic problem is that [`datetime.datetime.fromtimestamp`](https://docs.python.org/3.9/library/datetime.html#datetime.datetime.fromtimestamp) reads the timestamp as UTC and then converts it to the system timezone without attaching the timezone specifier. 

We can fix this by either keeping the timestamp as UTC:
```python
return datetime.datetime.fromtimestamp(mtime, datetime.timezone.utc)
```
or explicitly attaching the system timezone:
```python
return datetime.datetime.fromtimestamp(mtime).astimezone()
```

I'm happy to make a PR for whichever one you prefer.

**Comment by dairiki** [comment]
@Lexicality Thank you for the report.

As you note, currently, timestamps are returned as naive `datetime` instances, in the system timezone. At this point, I don't remember why I made that choice, but it is at least somewhat defensible:

1. Lektor's [`datetime`] type represents times in the *system tz* as naive `datetime`s, so it's not totally crazy for us to do the same.  E.g. when datetime's are parsed: if there is an explicit timezone in the input string, the result is a tz-aware datetime, but the only way to express a time in the "system zone" is to omit any timezone from the string, in which case it is parsed to a naive `datetime`.
2. `datetime.astimezone` [assumes that naive `datetime`s are in the system zone][assume].

In any case, I'm hesitant to change that behavior at this point for fear of breaking existing user code.  (I.e. returning aware `datetime`s would be an API change.)  I'm open to discussion, but my initial inclination is to leave it as it is.

----

Note that the [lektor-datetime-helpers] Lektor plugin provides two jinja filters that may help:
- `isoformat`: return iso-formatted version of datetime, always including zone offset
- `localize_datetime`: localizes naive `datetime`s to the system timezone



[`datetime`]: https://www.getlektor.com/docs/api/db/types/datetime/

[assume]: https://docs.python.org/3/library/datetime.html#datetime-objects:~:text=If%20self%20is%20naive%2C%20it%20is%20presumed%20to%20represent%20time%20in%20the%20system%20time%20zone.

[lektor-datetime-helpers]: https://github.com/dairiki/lektor-datetime-helpers

**Comment by Lexicality** [comment]
> Lektor's datetime type represents times in the system tz as naive datetimes

Ah, I didn't know that - it makes a lot of sense to maintain consistency with that. Thank you for the plugin suggestion!
